Update README.md
OfficeDev/office-js pull request #5164
Opened 2024-12-06 03:26 UTC by satyajit321

Missing # causing the internal reference link to be broken for "determine-if-centrally-deployed" leading to 404 not found error when clicked.

Corrected link:
https://github.com/OfficeDev/office-js/tree/release/add-in-ids#determine-if-centrally-deployed-add-ins-are-using-legacy-tokens

404 - page not found
The release branch of office-js does not contain the path  add-in-ids/determine-if-centrally-deployed-add-ins-are-using-legacy-tokens.

2024-12-12 22:20 UTC, lindalu-MSFT requested changes
I think we only need ONE link at the end of this section. We don't need it at the end of every sentence.

"For next steps, see [Determine if centrally deployed add-ins are using legacy tokens](#determine-if-centrally-deployed-add-ins-are-using-legacy-tokens)."

2024-12-12 22:21 UTC, lindalu-MSFT commented
@satyajit321

2024-12-13 07:12 UTC, satyajit321 commented
I'm fine with additional edits, I have only updated the hyperlinks issue. If content needs modification it can be done directly or seperately. I'm not sure what's next to be done here.

2024-12-13 21:03 UTC, lindalu-MSFT commented on add-in-ids/README.md
> +Add-ins without a value for the **AssetID** are centrally deployed. These can’t be found in the spreadsheet. For next steps, see [Determine if centrally deployed add-ins are using legacy tokens](#det
```suggestion
Add-ins without a value for the **AssetID** are centrally deployed. These can’t be found in the spreadsheet. 
```

2024-12-13 21:04 UTC, lindalu-MSFT commented on add-in-ids/README.md
> +Add-ins without a value for the **AssetID** are centrally deployed. These can’t be found in the spreadsheet.
```suggestion
Add-ins without a value for the **AssetID** are centrally deployed. These can’t be found in the spreadsheet. 

For next steps, see [Determine if centrally deployed add-ins are using legacy tokens](#determine-if-centrally-deployed-add-ins-are-using-legacy-tokens).
```

2024-12-13 21:04 UTC, lindalu-MSFT commented on add-in-ids/README.md
>  The command lists all add-ins you deployed on your tenant. If any add-ins have a value for the **AssetID** then they are deployed from the Microsoft store and you can search the `add-ins-using-exchan
```suggestion
The command lists all add-ins you deployed on your tenant. If any add-ins have a value for the **AssetID** then they are deployed from the Microsoft store and you can search the `add-ins-using-exchange-tokens.xlsx` spreadsheet to see if they use legacy tokens. 
```

2024-12-13 21:05 UTC, lindalu-MSFT commented on add-in-ids/README.md
>  The **MarketplaceAssetID** column will list an asset ID if the add-in was deployed from the Microsoft store. You can search the spreadsheet to see if these are using legacy tokens. For next steps, se
```suggestion
The **MarketplaceAssetID** column will list an asset ID if the add-in was deployed from the Microsoft store. You can search the spreadsheet to see if these are using legacy tokens. 
```

2024-12-13 21:06 UTC, lindalu-MSFT commented on add-in-ids/README.md
> +Add-ins that don't have a **MarketplaceAssetID** were deployed by the user from the organization or by sideloading. These aren’t listed in the spreadsheet and are either line-of-business add-ins or 3
```suggestion
Add-ins that don't have a **MarketplaceAssetID** were deployed by the user from the organization or by sideloading. These aren’t listed in the spreadsheet and are either line-of-business add-ins or 3rd party add-ins. For next steps, see [Determine if centrally deployed add-ins are using legacy tokens](#determine-if-centrally-deployed-add-ins-are-using-legacy-tokens).

For next steps, see [Determine if centrally deployed add-ins are using legacy tokens](#determine-if-centrally-deployed-add-ins-are-using-legacy-tokens).
```

2024-12-13 21:06 UTC, lindalu-MSFT commented on add-in-ids/README.md
> +Add-ins without a value for the **MarketplaceAssetID** are centrally deployed. These can’t be found in the spreadsheet. For next steps, see [Determine if centrally deployed add-ins are using legacy t
```suggestion
Add-ins without a value for the **MarketplaceAssetID** are centrally deployed. These can’t be found in the spreadsheet. 
```

2024-12-13 21:07 UTC, lindalu-MSFT commented on add-in-ids/README.md
>  The command lists all organization add-ins deployed on your tenant. The **MarketplaceAssetID** lists the asset ID of any add-ins deployed from the Microsoft store. You can search the spreadsheet to s
```suggestion
The command lists all organization add-ins deployed on your tenant. The **MarketplaceAssetID** lists the asset ID of any add-ins deployed from the Microsoft store. You can search the spreadsheet to see if these are using legacy tokens. 
```

2024-12-13 21:08 UTC, lindalu-MSFT commented on add-in-ids/README.md
> +Add-ins without a value for the **MarketplaceAssetID** are centrally deployed. These can’t be found in the spreadsheet.
```suggestion
Add-ins without a value for the **MarketplaceAssetID** are centrally deployed. These can’t be found in the spreadsheet. 

For next steps, see [Determine if centrally deployed add-ins are using legacy tokens](#determine-if-centrally-deployed-add-ins-are-using-legacy-tokens).
```

2024-12-13 21:09 UTC, lindalu-MSFT commented on add-in-ids/README.md
> +Add-ins that don't have a **MarketplaceAssetID** were deployed by the user from the organization or by sideloading. These aren’t listed in the spreadsheet and are either line-of-business add-ins or 3
```suggestion
Add-ins that don't have a **MarketplaceAssetID** were deployed by the user from the organization or by sideloading. These aren’t listed in the spreadsheet and are either line-of-business add-ins or 3rd party add-ins. 
```

2024-12-13 21:09 UTC, lindalu-MSFT approved these changes, later dismissed
I removed redundant sentences and added just one at the end of each section.

2024-12-13 21:14 UTC, lindalu-MSFT approved these changes

2024-12-13 22:49 UTC, merged